name: league_of_stats
version: '1.0'

config-version: 2

profile: my_dbt_profile 

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  league_of_stats:  # This should match the 'name' at the top
    +materialized: view  # Default materialization (view, table, incremental)